# Generated by Django 4.2.6 on 2023-10-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_studentscourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('en', 'Английский'), ('ru', 'Русский')], max_length=2, null=True, verbose_name='Язык обучения'),
        ),
    ]
